#!/bin/sh

JenkinsUrl="http://740ef5d8.ngrok.io/"

#watch spaces in Jenkins Project Names, they will need to be url encoded to %20
ProjectName="ucsmsdk"

echo ""
echo "Triggering Build on Jenkins server $JenkinsUrl"
echo ""

curl "$JenkinsUrl/job/$ProjectName/build"
